version: "3.7"
services:

# BASE DE DATOS 
  database:
    image: bitnami/postgresql:14.5.0
    restart: always
    volumes:
       - './db/data:/bitnami/postgresql'
       - './db/data.sql:/docker-entrypoint-initdb.d/data.sql:ro'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - 5432:5432
      

# REDIS SHRPS
  redis1:
    container_name: redis1
    image: 'bitnami/redis:7.0.4'
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    

  redis2:
    container_name: redis2
    image: 'bitnami/redis:7.0.4'
    restart: always
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    
  
  redis3:
    container_name: redis3
    image: bitnami/redis:7.0.4
    restart: always
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    

    
# SERVIDOR
  grpc_server:
    build: ./grpc_server/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=database
# BACKEND    
  backend:
    build: ./backend/
    environment:
      - REDIS_HOST= dbredis
    restart: always
    ports:
      - "3000:3000"