version: "3.7"
services:

# BASE DE DATOS 
  database:
    image: bitnami/postgresql:14.5.0
    restart: always
    volumes:
       - './db/data:/bitnami/postgresql'
       - './db/data.sql:/docker-entrypoint-initdb.d/data.sql:ro'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - 5432:5432
      
# REDIS
  dbredis:
    build: ./redis/
    restart: always
    
    
# SERVIDOR
  grpc_server:
    build: ./grpc_server/
    restart: always
  backend:
    build: ./backend/
    environment:
      - REDIS_HOST= dbredis
    restart: always
    ports:
      - "3000:3000"

