version: "3.7"
services:
  database:
    image: bitnami/postgresql:14.5.0
    restart: always
    volumes:
       - './db/data:/bitnami/postgresql'
       - './db/data.sql:/docker-entrypoint-initdb.d/data.sql:ro'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - 5432:5432
